### ISSUE TITLE
add tracing

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/rdsn#126]
for profiling slow query

**Comment by neverchanje** [comment]
The original goal of this issue is to provide rDSN framework with some visualization tools based on browser, which allows us to easily debugging without ssh to specified server.

The first step is to test the http message parser in rDSN, so that we can register builtin services such as event tracing, threads info view, etc. The final result will resemble the [brpc builtin services](https://github.com/brpc/brpc/tree/master/src/brpc/builtin).

**Comment by neverchanje** [comment]
1.
